# Generated by Django 5.0.7 on 2024-12-31 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0002_matiere_rename_id_enseignant_salle_enseignant_and_more'),
        ('enseignant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assiduite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('present', models.BooleanField(default=False)),
                ('observation', models.TextField(blank=True, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.eleve')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignant.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('observation', models.TextField(blank=True, null=True)),
                ('coefficient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.coefficient')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.eleve')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignant.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.matiere')),
            ],
        ),
    ]
