# Generated by Django 5.0.7 on 2025-02-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0002_assiduite_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enseignant',
            old_name='matiere',
            new_name='matiere_enseignee',
        ),
        migrations.RemoveField(
            model_name='note',
            name='coefficient',
        ),
    ]
