# Generated by Django 5.0.7 on 2025-03-05 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0007_emploidetemp'),
        ('enseignant', '0004_assiduite_heure_assiduite_salle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='observation',
            new_name='appreciation',
        ),
        migrations.AddField(
            model_name='note',
            name='salle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrateur.salle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='sequence',
            field=models.CharField(choices=[('1', 'Séquence 1'), ('2', 'Séquence 2'), ('3', 'Séquence 3'), ('4', 'Séquence 4'), ('5', 'Séquence 5'), ('6', 'Séquence 6')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
