# Generated by Django 5.0.7 on 2024-09-03 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='DateCreation',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 14, 36, 56, 425202)),
        ),
    ]
