# Generated by Django 5.0.7 on 2025-02-06 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0003_eleve_salle_alter_eleve_tel_parent'),
        ('enseignant', '0003_rename_matiere_enseignant_matiere_enseignee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='matiere',
            name='coefficient',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matiere',
            name='enseignant',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='enseignant.enseignant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eleve',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.salle'),
        ),
        migrations.DeleteModel(
            name='Coefficient',
        ),
    ]
