# Generated by Django 5.0.7 on 2025-02-08 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0004_niveau_matiere_coefficient_matiere_enseignant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='niveau',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrateur.niveau'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salle',
            name='niveau',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrateur.niveau'),
            preserve_default=False,
        ),
    ]
