# Generated by Django 5.0.7 on 2025-02-27 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0005_matiere_niveau_salle_niveau'),
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='parent',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='parent.parent'),
            preserve_default=False,
        ),
    ]
