# Generated by Django 5.0.7 on 2025-03-05 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0006_eleve_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploiDeTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=20)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('matiere', models.CharField(max_length=100)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.salle')),
            ],
        ),
    ]
